In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read in data
playoff_box_scores = pd.read_csv('../NBA_Player_Evolution_2020-2024/play_off_box_scores_2010_2024.csv')

#Change season_year and game_date to date-time format
playoff_box_scores['game_date'] = pd.to_datetime(playoff_box_scores['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
playoff_box_scores[(playoff_box_scores['season_year']>='2020-21') & (playoff_box_scores['season_year']<='2023-24')]

#Select the columns I will be using to make it easier to work with
playoff_box_scores = playoff_box_scores[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamSlug', 'personId', 'personName', 'position', 'minutes', 'fieldGoalsPercentage', 'threePointersPercentage', 'freeThrowsPercentage', 'points', 'plusMinusPoints', 'assists']]
playoff_box_scores

,season_year,game_date,gameId,teamId,teamTricode,teamSlug,personId,personName,position,minutes,fieldGoalsPercentage,threePointersPercentage,freeThrowsPercentage,points,plusMinusPoints,assists
0,2011-12,2012-06-03,41100304,1610612748,MIA,heat,436,Juwan Howard,NaN,NaN,0.0,0.0,0.0,0,0,0
1,2011-12,2012-06-09,41100307,1610612748,MIA,heat,436,Juwan Howard,NaN,0:28,0.0,0.0,0.0,0,0,0
2,2010-11,2011-06-05,41000403,1610612748,MIA,heat,436,Juwan Howard,NaN,6:25,0.0,0.0,0.5,1,6,1
3,2011-12,2012-04-28,41100111,1610612748,MIA,heat,436,Juwan Howard,NaN,5:12,0.0,0.0,0.0,0,3,0
4,2011-12,2012-05-15,41100202,1610612748,MIA,heat,436,Juwan Howard,NaN,NaN,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31180,2023-24,2024-04-20,42300161,1610612756,PHX,suns,1629642,Nassir Little,NaN,3:37,1.0,0.0,0.0,2,-5,0
31181,2023-24,2024-04-28,42300164,1610612756,PHX,suns,201152,Thaddeus Young,NaN,NaN,0.0,0.0,0.0,0,0,0
31182,2023-24,2024-04-23,42300162,1610612756,PHX,suns,201152,Thaddeus Young,NaN,NaN,0.0,0.0,0.0,0,0,0
31183,2023-24,2024-04-26,42300163,1610612756,PHX,suns,201152,Thaddeus Young,NaN,NaN,0.0,0.0,0.0,0,0,0
31184,2023-24,2024-04-20,42300161,1610612756,PHX,suns,201152,Thaddeus Young,NaN,3:37,0.0,0.0,0.0,0,-5,0

In [3]:
# Read in data
team_playoff_totals = pd.read_csv('../NBA_Player_Evolution_2020-2024/play_off_totals_2010_2024.csv')

#Change season_year and game_date to date-time format
team_playoff_totals['GAME_DATE'] = pd.to_datetime(team_playoff_totals['GAME_DATE'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
team_playoff_totals[(team_playoff_totals['SEASON_YEAR']>='2020-21') & (team_playoff_totals['SEASON_YEAR']<='2023-24')]

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
team_playoff_totals = team_playoff_totals[['SEASON_YEAR', 'GAME_DATE', 'GAME_ID', 'TEAM_ID', 'TEAM_NAME', 'FG_PCT', 'FG3_PCT', 'FT_PCT', 'PTS', 'PTS_RANK', 'AST', 'AST_RANK', 'PLUS_MINUS_RANK']]
team_playoff_totals

,SEASON_YEAR,GAME_DATE,GAME_ID,TEAM_ID,TEAM_NAME,FG_PCT,FG3_PCT,FT_PCT,PTS,PTS_RANK,AST,AST_RANK,PLUS_MINUS_RANK
0,2010-11,2011-05-10,41000205,1610612737,Atlanta Hawks,0.479,0.083,0.824,83,140,20,43,139
1,2010-11,2011-05-02,41000201,1610612737,Atlanta Hawks,0.513,0.538,0.800,103,24,20,43,39
2,2010-11,2011-05-04,41000202,1610612737,Atlanta Hawks,0.338,0.231,0.750,73,159,14,137,145
3,2010-11,2011-04-19,41000132,1610612737,Atlanta Hawks,0.395,0.350,0.647,82,144,15,123,106
4,2010-11,2011-04-26,41000135,1610612737,Atlanta Hawks,0.362,0.250,0.688,76,157,15,123,159
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2357,2023-24,2024-04-20,42300161,1610612756,Phoenix Suns,0.440,0.321,0.800,95,129,16,156,153
2358,2023-24,2024-04-20,42300131,1610612739,Cleveland Cavaliers,0.444,0.267,0.810,97,120,21,103,31
2359,2023-24,2024-04-20,42300161,1610612750,Minnesota Timberwolves,0.500,0.375,0.909,120,21,26,35,11
2360,2023-24,2024-04-20,42300111,1610612755,Philadelphia 76ers,0.444,0.343,0.909,104,92,17,149,106
2361,2023-24,2024-04-20,42300131,1610612753,Orlando Magic,0.326,0.216,0.633,83,161,16,156,133

In [4]:
regular_part_1 = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_box_scores_2010_2024_part_1.csv')

#Change season_year and game_date to date-time format
regular_part_1['game_date'] = pd.to_datetime(regular_part_1['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
#regular_part_1[(regular_part_1['season_year']>='2020-21') & (regular_part_1['season_year']<='2023-24')]
regular_part_1 = regular_part_1[regular_part_1['game_date']>='2020-03-01']

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_part_1 = regular_part_1[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamName', 'personId', 'personName', 'position', 'minutes', 'assists', 'points', 'fieldGoalsPercentage', 'threePointersPercentage', 'plusMinusPoints', 'freeThrowsPercentage']]

regular_part_1['season_year'].unique()
regular_part_1['minutes'].info()
regular_part_1

<class 'pandas.core.series.Series'>
Index: 42133 entries, 2062 to 140999
Series name: minutes
Non-Null Count  Dtype
--------------  -----
34537 non-null  object
dtypes: object(1)
memory usage: 658.3+ KB

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,position,minutes,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
2062,2019-20,2020-03-06,21900930,1610612737,ATL,Hawks,1713,Vince Carter,NaN,16:45,0,8,0.750,0.667,1,0.0
2084,2019-20,2020-03-09,21900957,1610612737,ATL,Hawks,1713,Vince Carter,NaN,15:08,1,9,0.500,0.600,0,0.0
2093,2019-20,2020-03-11,21900969,1610612737,ATL,Hawks,1713,Vince Carter,NaN,12:40,0,5,0.400,0.500,6,0.0
2106,2019-20,2020-03-07,21900943,1610612737,ATL,Hawks,1713,Vince Carter,NaN,18:54,1,5,0.286,0.167,8,0.0
2157,2019-20,2020-03-02,21900905,1610612737,ATL,Hawks,1713,Vince Carter,NaN,15:12,1,6,0.222,0.286,-16,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140972,2019-20,2020-03-10,21900963,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0.000,0.000,0,0.0
140981,2019-20,2020-03-05,21900927,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0.000,0.000,0,0.0
140983,2019-20,2020-08-04,21901261,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0.000,0.000,0,0.0
140998,2019-20,2020-08-11,21901298,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0.000,0.000,0,0.0
140999,2019-20,2020-08-02,21901248,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0.000,0.000,0,0.0

In [5]:
regular_part_2 = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_box_scores_2010_2024_part_2.csv')

#Change season_year and game_date to date-time format
regular_part_2['game_date'] = pd.to_datetime(regular_part_2['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
#regular_part_2[(regular_part_2['season_year']>='2020-21') & (regular_part_2['season_year']<='2023-24')]
regular_part_2 = regular_part_2[regular_part_2['game_date']>='2020-03-01']

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_part_2 = regular_part_2[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamName', 'personId', 'personName', 'position', 'minutes', 'assists', 'points', 'fieldGoalsPercentage', 'threePointersPercentage', 'plusMinusPoints', 'freeThrowsPercentage']]
regular_part_2['season_year'].unique()
regular_part_2['minutes'].info()

<class 'pandas.core.series.Series'>
Index: 42911 entries, 1441 to 140866
Series name: minutes
Non-Null Count  Dtype
--------------  -----
34785 non-null  object
dtypes: object(1)
memory usage: 670.5+ KB

In [6]:
regular_part_3 = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_box_scores_2010_2024_part_3.csv')

#Change season_year and game_date to date-time format
regular_part_3['game_date'] = pd.to_datetime(regular_part_3['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)

regular_part_3 = regular_part_3[regular_part_3['game_date']>='2020-03-01']
#regular_part_3['season_year'] = regular_part_3[regular_part_3['season_year'].isin(filtered_years)]


#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_part_3 = regular_part_3[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamName', 'personId', 'personName', 'minutes', 'assists', 'points', 'fieldGoalsPercentage', 'threePointersPercentage', 'plusMinusPoints', 'freeThrowsPercentage']]

regular_part_3['season_year'].unique()
regular_part_3['minutes'].info()

<class 'pandas.core.series.Series'>
Index: 43231 entries, 922 to 141491
Series name: minutes
Non-Null Count  Dtype
--------------  -----
35556 non-null  object
dtypes: object(1)
memory usage: 675.5+ KB

In [7]:
regular_season_totals = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_totals_2010_2024.csv')

#Change season_year and game_date to date-time format
regular_season_totals['GAME_DATE'] = pd.to_datetime(regular_season_totals['GAME_DATE'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
regular_season_totals[(regular_season_totals['SEASON_YEAR']>='2020-21') & (regular_season_totals['SEASON_YEAR']<='2023-24')]

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_season_totals[['SEASON_YEAR', 'GAME_DATE', 'GAME_ID', 'TEAM_ID', 'TEAM_NAME', 'FG_PCT', 'FG3_PCT', 'FT_PCT', 'AST', 'AST_RANK', 'PTS', 'PTS_RANK', 'PLUS_MINUS_RANK']]

,SEASON_YEAR,GAME_DATE,GAME_ID,TEAM_ID,TEAM_NAME,FG_PCT,FG3_PCT,FT_PCT,AST,AST_RANK,PTS,PTS_RANK,PLUS_MINUS_RANK
0,2022-23,2023-04-09,22201230,1610612744,Golden State Warriors,0.604,0.551,0.875,47,1,157,3,1
1,2020-21,2020-12-29,22000051,1610612749,Milwaukee Bucks,0.554,0.569,0.867,32,146,144,14,7
2,2013-14,2013-12-16,21300359,1610612751,Brooklyn Nets,0.603,0.600,0.577,35,22,130,19,12
3,2013-14,2013-12-14,21300347,1610612757,Portland Trail Blazers,0.559,0.568,0.700,41,2,139,4,15
4,2018-19,2019-04-07,21801200,1610612745,Houston Rockets,0.530,0.474,0.762,34,84,149,4,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33311,2022-23,2023-01-23,22200710,1610612766,Charlotte Hornets,0.447,0.125,0.706,22,1756,102,2077,2211
33312,2022-23,2023-01-29,22200754,1610612746,LA Clippers,0.416,0.105,0.852,17,2338,99,2220,2339
33313,2018-19,2019-03-23,21801090,1610612741,Chicago Bulls,0.359,0.125,0.750,16,2339,83,2439,2412
33314,2021-22,2021-10-30,22100078,1610612738,Boston Celtics,0.411,0.077,0.880,23,1407,112,1081,1321
33315,2013-14,2013-12-30,21300454,1610612763,Memphis Grizzlies,0.449,0.000,0.750,19,1681,91,1931,1417

In [8]:
# Combine the 3 regular season stats for easier analysis and remove duplicates
two_regular_season = pd.merge(regular_part_1, regular_part_2, how='outer')
#all_regular_season = all_regular_season.drop_duplicates()
two_regular_season

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,position,minutes,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
0,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,101107,Marvin Williams,NaN,19:37,2,0,0.000,0.000,-11,0.000
1,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,101141,Ersan Ilyasova,NaN,NaN,0,0,0.000,0.000,0,0.000
2,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201572,Brook Lopez,C,26:25,0,16,0.364,0.200,16,0.778
3,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201577,Robin Lopez,NaN,13:18,0,2,0.200,0.000,-12,0.000
4,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201588,George Hill,NaN,25:43,2,11,0.364,0.250,2,0.667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85039,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1629611,Terance Mann,G,27:40,2,24,0.714,0.333,-4,1.000
85040,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1629875,Xavier Moon,G,46:21,6,14,0.273,0.222,-7,0.000
85041,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1630527,Brandon Boston Jr.,NaN,30:53,3,15,0.313,0.333,-4,0.750
85042,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1630538,Bones Hyland,NaN,NaN,0,0,0.000,0.000,0,0.000
85043,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1641738,Kobe Brown,NaN,38:26,4,9,0.400,0.333,-10,0.000

In [9]:
#merge the combined df with the 3rd regular season data
all_regular_season = pd.merge(two_regular_season, regular_part_3, how='outer')

#remove : and the seconds from the mm:ss fill NaN with 0:0 to account for errors and change to string because the object column doesnt allow
all_regular_season['minutes'] = (all_regular_season['minutes'].fillna('0:0').str.split(':').str[0].astype(int))

#filter for players that played 20 or minutes for more consistent data
all_regular_season = all_regular_season[all_regular_season['minutes'] >= 20]

all_regular_season

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,position,minutes,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
2,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201572,Brook Lopez,C,26,0,16,0.364,0.200,16,0.778
4,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201588,George Hill,NaN,25,2,11,0.364,0.250,2,0.667
5,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,202083,Wesley Matthews,F,27,2,8,0.273,0.286,11,0.000
6,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,202339,Eric Bledsoe,G,22,2,4,0.250,0.000,6,0.000
7,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,203507,Giannis Antetokounmpo,F,34,6,41,0.607,0.250,22,0.857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128264,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1627734,Domantas Sabonis,NaN,27,9,18,0.700,0.000,37,1.000
128265,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1628368,De'Aaron Fox,NaN,25,3,24,0.714,0.667,13,1.000
128270,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1630558,Davion Mitchell,NaN,21,3,11,0.364,0.600,33,0.000
128271,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1631099,Keegan Murray,NaN,27,1,12,0.333,0.286,26,1.000
128272,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1631165,Keon Ellis,NaN,24,2,13,0.444,0.500,30,1.000

In [10]:
grouped_data = all_regular_season.groupby(['season_year', 'personName','personId', 'plusMinusPoints']).agg({'minutes': 'mean', 'points': 'mean', 'assists': 'mean','fieldGoalsPercentage': 'mean'}).reset_index()

In [11]:
#filter for the year 2019-2020
year_2019_20 = grouped_data[grouped_data['season_year']=='2019-20']
year_2019_20

,season_year,personName,personId,plusMinusPoints,minutes,points,assists,fieldGoalsPercentage
0,2019-20,Aaron Gordon,203932,-13,31.0,8.0,9.0,0.375
1,2019-20,Aaron Gordon,203932,-12,32.0,20.0,3.0,0.533
2,2019-20,Aaron Gordon,203932,-7,20.0,9.0,5.0,0.333
3,2019-20,Aaron Gordon,203932,8,35.0,11.0,9.0,0.500
4,2019-20,Aaron Gordon,203932,18,37.0,15.0,4.0,0.400
...,...,...,...,...,...,...,...,...
2015,2019-20,Zion Williamson,1629627,0,32.0,25.0,3.0,0.526
2016,2019-20,Zion Williamson,1629627,1,33.0,19.0,2.5,0.639
2017,2019-20,Zion Williamson,1629627,8,25.0,23.0,5.0,0.429
2018,2019-20,Zion Williamson,1629627,20,31.0,23.0,1.0,0.600
2019,2019-20,Zylan Cheatham,1629597,2,20.0,8.0,1.0,1.000

In [12]:
#filter for the year 2020-2021
year_2020_21 = grouped_data[grouped_data['season_year']=='2020-21']
year_2020_21

,season_year,personName,personId,plusMinusPoints,minutes,points,assists,fieldGoalsPercentage
2020,2020-21,Aaron Gordon,203932,-27,28.0,9.0,2.0,0.308
2021,2020-21,Aaron Gordon,203932,-23,23.0,4.5,3.0,0.118
2022,2020-21,Aaron Gordon,203932,-17,35.0,21.0,8.0,0.571
2023,2020-21,Aaron Gordon,203932,-15,23.0,9.0,3.0,0.600
2024,2020-21,Aaron Gordon,203932,-14,29.0,10.0,1.0,0.571
...,...,...,...,...,...,...,...,...
11256,2020-21,Zion Williamson,1629627,20,22.0,23.0,2.0,0.750
11257,2020-21,Zion Williamson,1629627,24,32.0,27.0,5.0,0.813
11258,2020-21,Zion Williamson,1629627,25,28.0,27.0,5.0,0.692
11259,2020-21,Zion Williamson,1629627,29,20.0,20.0,7.0,0.600
11260,2020-21,Zion Williamson,1629627,37,32.0,28.0,6.0,0.857

In [13]:
#filter for the year 2021-2022
year_2021_22 = grouped_data[grouped_data['season_year']=='2021-22']
year_2021_22

,season_year,personName,personId,plusMinusPoints,minutes,points,assists,fieldGoalsPercentage
11261,2021-22,Aaron Gordon,203932,-28,27.0,8.0,1.0,0.3330
11262,2021-22,Aaron Gordon,203932,-27,27.0,9.0,0.0,0.3330
11263,2021-22,Aaron Gordon,203932,-18,21.0,13.0,0.0,0.6000
11264,2021-22,Aaron Gordon,203932,-16,29.5,16.0,3.5,0.5275
11265,2021-22,Aaron Gordon,203932,-15,33.5,17.0,3.5,0.5500
...,...,...,...,...,...,...,...,...
21330,2021-22,Ziaire Williams,1630533,13,23.0,4.0,0.0,0.5000
21331,2021-22,Ziaire Williams,1630533,14,25.5,8.5,2.0,0.4855
21332,2021-22,Ziaire Williams,1630533,18,26.0,5.5,3.0,0.3145
21333,2021-22,Ziaire Williams,1630533,21,25.0,14.0,0.0,0.6250
21334,2021-22,Ziaire Williams,1630533,32,21.0,16.0,1.0,0.6670

In [14]:
#filter for the year 2022-2023
year_2022_23 = grouped_data[grouped_data['season_year']=='2022-23']
year_2022_23

,season_year,personName,personId,plusMinusPoints,minutes,points,assists,fieldGoalsPercentage
21335,2022-23,A.J. Lawson,1630639,-19,22.0,12.000000,0.000000,0.556000
21336,2022-23,A.J. Lawson,1630639,-13,23.0,10.000000,1.000000,0.444000
21337,2022-23,AJ Green,1631260,-2,23.0,15.000000,1.000000,0.625000
21338,2022-23,AJ Green,1631260,9,21.0,7.000000,1.000000,0.333000
21339,2022-23,AJ Griffin,1631100,-21,20.0,6.000000,1.000000,0.333000
...,...,...,...,...,...,...,...,...
31080,2022-23,Zion Williamson,1629627,19,34.0,25.666667,6.666667,0.646667
31081,2022-23,Zion Williamson,1629627,20,26.0,32.000000,1.000000,0.778000
31082,2022-23,Zion Williamson,1629627,21,35.0,26.000000,6.000000,0.889000
31083,2022-23,Zion Williamson,1629627,28,28.0,19.500000,6.000000,0.536000
31084,2022-23,Zion Williamson,1629627,30,36.0,35.000000,4.000000,0.765000

In [15]:
#filter for the year 2023-2024
year_2023_24 = grouped_data[grouped_data['season_year']=='2023-24']
year_2023_24

,season_year,personName,personId,plusMinusPoints,minutes,points,assists,fieldGoalsPercentage
31085,2023-24,A.J. Lawson,1630639,-18,23.0,12.0,2.0,0.3850
31086,2023-24,A.J. Lawson,1630639,-4,21.0,2.0,2.0,0.1670
31087,2023-24,A.J. Lawson,1630639,2,23.0,8.0,1.0,0.7500
31088,2023-24,A.J. Lawson,1630639,16,30.0,17.0,3.0,0.7000
31089,2023-24,A.J. Lawson,1630639,21,24.0,14.0,2.0,0.5000
...,...,...,...,...,...,...,...,...
40872,2023-24,Zion Williamson,1629627,21,32.5,26.0,4.5,0.6175
40873,2023-24,Zion Williamson,1629627,23,29.0,19.0,7.0,0.6670
40874,2023-24,Zion Williamson,1629627,26,32.0,36.0,2.0,0.7650
40875,2023-24,Zion Williamson,1629627,28,25.0,16.0,9.0,0.6360
40876,2023-24,Zion Williamson,1629627,32,29.0,26.0,5.0,0.7500

In [55]:
#find the agg average of 5 columns from 2022-23
performance_score5 = year_2019_20.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

#Calculate personal performance score to rank players
year_2019_20['performance_score5'] = (
    year_2019_20['points'] +
    year_2019_20['assists'] +
    year_2019_20['fieldGoalsPercentage'] +
    year_2019_20['plusMinusPoints']
)

year_2019_20_top_5 = year_2019_20.nlargest(5, 'performance_score5')
year_2019_20_bottom_5= year_2019_20.nsmallest(5, 'performance_score5')

C:\Users\jswin\AppData\Local\Temp\ipykernel_8036\1158748084.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_2019_20['performance_score5'] = (

In [57]:
year_2019_20_top_5

,season_year,personName,personId,plusMinusPoints,minutes,points,assists,fieldGoalsPercentage,performance_score5
347,2019-20,Damian Lillard,203081,8,41.0,61.0,8.0,0.531,77.531
1826,2019-20,T.J. Warren,203933,18,40.0,53.0,3.0,0.690,74.690
1073,2019-20,Jrue Holiday,201950,27,35.0,37.0,8.0,0.650,72.650
238,2019-20,Caris LeVert,1627747,15,35.0,51.0,5.0,0.654,71.654
1187,2019-20,Khris Middleton,203114,30,34.0,33.0,8.0,0.643,71.643

In [59]:
year_2019_20_bottom_5

,season_year,personName,personId,plusMinusPoints,minutes,points,assists,fieldGoalsPercentage,performance_score5
1480,2019-20,Myles Turner,1626167,-39,30.0,7.0,0.0,0.333,-31.667
186,2019-20,Bruno Fernando,1628981,-31,22.0,2.0,3.0,0.125,-25.875
423,2019-20,De'Andre Hunter,1629631,-35,30.0,6.0,3.0,0.273,-25.727
758,2019-20,Harrison Barnes,203084,-37,24.0,12.0,0.0,0.500,-24.500
450,2019-20,DeMarre Carroll,201960,-29,24.0,5.0,1.0,0.400,-22.600

In [71]:
#find the agg average of 5 columns from 2022-23
performance_score20_21 = year_2020_21.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

#Calculate personal performance score to rank players
performance_score20_21['performance_score4'] = (
    performance_score20_21['points'] +
    performance_score20_21['assists'] +
    performance_score20_21['fieldGoalsPercentage'] +
    performance_score20_21['plusMinusPoints']
)

year_2020_21_top_5 = performance_score20_21.nlargest(5, 'performance_score4')
year_2020_21_bottom_5= performance_score20_21.nsmallest(5, 'performance_score4')

In [73]:
year_2020_21_top_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score4
280,2020-21,Kevin Durant,27.865079,6.007937,33.428571,0.552643,9.428571,43.854230
426,2020-21,Stephen Curry,31.149550,5.666667,33.472072,0.476981,4.378378,41.671576
168,2020-21,Giannis Antetokounmpo,28.329167,5.635417,32.852083,0.573281,6.975000,41.512865
83,2020-21,Damian Lillard,27.950417,7.649167,34.478333,0.439211,4.225000,40.263795
297,2020-21,Kyrie Irving,26.144444,6.272222,34.288889,0.499225,6.966667,39.882558

In [75]:
year_2020_21_bottom_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score4
21,2020-21,Anthony Tolliver,0.0,0.00,21.00,0.00000,-18.0,-18.00000
266,2020-21,Karim Mane,2.0,1.00,21.00,0.00000,-20.0,-17.00000
241,2020-21,Jordan Bell,4.0,5.00,31.00,0.22200,-22.0,-12.77800
51,2020-21,Cam Reynolds,9.0,2.00,31.00,0.21400,-23.0,-11.78600
242,2020-21,Jordan Bone,6.0,1.75,25.25,0.34375,-18.0,-9.90625

In [77]:
#find the agg average of 5 columns from 2022-23
performance_score21_22 = year_2021_22.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

#Calculate personal performance score to rank players
performance_score21_22['performance_score3'] = (
    performance_score21_22['points'] +
    performance_score21_22['assists'] +
    performance_score21_22['fieldGoalsPercentage'] +
    performance_score21_22['plusMinusPoints']
)

year_2021_22_top_5 = performance_score21_22.nlargest(5, 'performance_score3')
year_2021_22_bottom_5= performance_score21_22.nsmallest(5, 'performance_score3')

In [79]:
year_2021_22_top_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score3
382,2021-22,Nikola Jokic,27.419686,7.846516,32.964402,0.611087,5.975610,41.852899
472,2021-22,Trae Young,28.582171,9.451938,34.093411,0.475015,3.232558,41.741682
329,2021-22,Luka Doncic,27.992248,8.910853,34.437984,0.447671,3.534884,40.885655
292,2021-22,Kevin Durant,30.532895,6.190789,36.986842,0.527526,3.421053,40.672263
234,2021-22,Jayson Tatum,26.644737,4.609649,35.155702,0.456866,8.842105,40.553357

In [81]:
year_2021_22_bottom_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score3
131,2021-22,Didi Louzada,3.000000,0.000000,26.000000,0.200000,-31.000000,-27.800000
493,2021-22,Udonis Haslem,2.000000,1.000000,20.000000,0.200000,-23.000000,-19.800000
355,2021-22,Melvin Frazier Jr.,10.666667,0.333333,39.333333,0.270333,-30.666667,-19.396333
275,2021-22,Juwan Morgan,5.000000,1.000000,27.000000,0.667000,-25.000000,-18.333000
235,2021-22,Jeff Dowtin Jr.,4.000000,3.000000,30.000000,0.250000,-22.000000,-14.750000

In [97]:
#find the agg average of 5 columns from 2022-23
performance_score22_23 = year_2022_23.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

#Calculate personal performance score to rank players
performance_score22_23['performance_score1'] = (
    performance_score22_23['points'] +
    performance_score22_23['assists'] +
    performance_score22_23['fieldGoalsPercentage'] +
    performance_score22_23['plusMinusPoints']
)

year_2022_23_top_5 = performance_score22_23.nlargest(5, 'performance_score1')
year_2022_23_bottom_5= performance_score22_23.nsmallest(5, 'performance_score1')

In [99]:
year_2022_23_top_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score1
315,2022-23,Mac McClung,20.000000,9.000000,33.000000,0.471000,29.000000,58.471000
203,2022-23,Jared Butler,25.000000,4.000000,45.000000,0.476000,16.000000,45.476000
230,2022-23,Joel Embiid,33.674020,4.225490,34.526961,0.548174,5.676471,44.124154
310,2022-23,Luka Doncic,32.335043,8.152564,36.296581,0.487132,1.769231,42.743970
361,2022-23,Nikola Jokic,23.393810,9.905238,32.619524,0.649303,8.400000,42.348350

In [101]:
year_2022_23_bottom_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score1
57,2022-23,Chance Comanche,7.0,0.0,20.000,0.600000,-29.00,-21.400000
241,2022-23,Jordan Hall,3.0,2.0,20.000,0.250000,-16.00,-10.750000
231,2022-23,John Butler Jr.,7.5,1.5,26.625,0.347875,-15.25,-5.902125
356,2022-23,Nerlens Noel,3.5,1.5,20.500,0.450000,-11.00,-5.550000
213,2022-23,Jay Scrubb,11.0,1.0,27.000,0.667000,-18.00,-5.333000

In [61]:
#find the agg average of 5 columns from 2023-24
performance_score23_24 = year_2023_24.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

#Calculate personal performance score to rank players
performance_score23_24['performance_score2'] = (
    performance_score23_24['points'] +
    performance_score23_24['assists'] +
    performance_score23_24['fieldGoalsPercentage'] +
    performance_score23_24['plusMinusPoints']
)

In [93]:
year_2023_24_top_5 = performance_score2.nlargest(5, 'performance_score2')
year_2023_24_bottom_5= performance_score2.nsmallest(5, 'performance_score2')

In [95]:
year_2023_24_top_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score2
309,2023-24,Luka Doncic,33.432917,9.567917,36.641667,0.484336,3.975000,47.460170
234,2023-24,Joel Embiid,34.482143,5.642857,33.184524,0.523970,5.892857,46.541827
363,2023-24,Nikola Jokic,27.293750,8.840417,34.483750,0.620709,7.625000,44.379876
420,2023-24,Shai Gilgeous-Alexander,29.104472,6.054878,32.763008,0.534702,7.780488,43.474539
196,2023-24,Jalen Brunson,29.235985,6.776515,35.358333,0.473196,6.454545,42.940242

In [69]:
year_2023_24_bottom_5

,season_year,personName,points,assists,minutes,fieldGoalsPercentage,plusMinusPoints,performance_score2
355,2023-24,Nathan Mensah,1.333333,1.0,23.0,0.277667,-27.0,-24.3890
290,2023-24,Kobi Simmons,2.000000,6.0,24.0,0.167000,-25.0,-16.8330
99,2023-24,Dariq Whitehead,2.000000,3.0,21.0,0.200000,-16.0,-10.8000
436,2023-24,Taze Moore,12.000000,4.0,30.0,0.357000,-27.0,-10.6430
444,2023-24,Timmy Allen,2.750000,1.0,27.0,0.187500,-13.0,-9.0625

year_2019_20.to_csv('year_2019_20.csv', index=False)

year_2020_21.to_csv('year_2020_21.csv', index=False)

year_2021_22.to_csv('year_2021_22.csv', index=False)

year_2022_23.to_csv('year_2022_23.csv', index=False)

year_2023_24.to_csv('year_2023_24.csv', index=False)