In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read in data
playoff_box_scores = pd.read_csv('../NBA_Player_Evolution_2020-2024/play_off_box_scores_2010_2024.csv')

#Change season_year and game_date to date-time format
playoff_box_scores['game_date'] = pd.to_datetime(playoff_box_scores['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
playoff_box_scores[(playoff_box_scores['season_year']>='2020-21') & (playoff_box_scores['season_year']<='2023-24')]

#Select the columns I will be using to make it easier to work with
playoff_box_scores = playoff_box_scores[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamSlug', 'personId', 'personName', 'position', 'minutes', 'fieldGoalsPercentage', 'threePointersPercentage', 'freeThrowsPercentage', 'points', 'plusMinusPoints', 'assists']]
playoff_box_scores

,season_year,game_date,gameId,teamId,teamTricode,teamSlug,personId,personName,position,minutes,fieldGoalsPercentage,threePointersPercentage,freeThrowsPercentage,points,plusMinusPoints,assists
0,2011-12,2012-06-03,41100304,1610612748,MIA,heat,436,Juwan Howard,NaN,NaN,0.0,0.0,0.0,0,0,0
1,2011-12,2012-06-09,41100307,1610612748,MIA,heat,436,Juwan Howard,NaN,0:28,0.0,0.0,0.0,0,0,0
2,2010-11,2011-06-05,41000403,1610612748,MIA,heat,436,Juwan Howard,NaN,6:25,0.0,0.0,0.5,1,6,1
3,2011-12,2012-04-28,41100111,1610612748,MIA,heat,436,Juwan Howard,NaN,5:12,0.0,0.0,0.0,0,3,0
4,2011-12,2012-05-15,41100202,1610612748,MIA,heat,436,Juwan Howard,NaN,NaN,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31180,2023-24,2024-04-20,42300161,1610612756,PHX,suns,1629642,Nassir Little,NaN,3:37,1.0,0.0,0.0,2,-5,0
31181,2023-24,2024-04-28,42300164,1610612756,PHX,suns,201152,Thaddeus Young,NaN,NaN,0.0,0.0,0.0,0,0,0
31182,2023-24,2024-04-23,42300162,1610612756,PHX,suns,201152,Thaddeus Young,NaN,NaN,0.0,0.0,0.0,0,0,0
31183,2023-24,2024-04-26,42300163,1610612756,PHX,suns,201152,Thaddeus Young,NaN,NaN,0.0,0.0,0.0,0,0,0
31184,2023-24,2024-04-20,42300161,1610612756,PHX,suns,201152,Thaddeus Young,NaN,3:37,0.0,0.0,0.0,0,-5,0

In [3]:
# Read in data
team_playoff_totals = pd.read_csv('../NBA_Player_Evolution_2020-2024/play_off_totals_2010_2024.csv')

#Change season_year and game_date to date-time format
team_playoff_totals['GAME_DATE'] = pd.to_datetime(team_playoff_totals['GAME_DATE'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
team_playoff_totals[(team_playoff_totals['SEASON_YEAR']>='2020-21') & (team_playoff_totals['SEASON_YEAR']<='2023-24')]

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
team_playoff_totals = team_playoff_totals[['SEASON_YEAR', 'GAME_DATE', 'GAME_ID', 'TEAM_ID', 'TEAM_NAME', 'FG_PCT', 'FG3_PCT', 'FT_PCT', 'PTS', 'PTS_RANK', 'AST', 'AST_RANK', 'PLUS_MINUS_RANK']]
team_playoff_totals

,SEASON_YEAR,GAME_DATE,GAME_ID,TEAM_ID,TEAM_NAME,FG_PCT,FG3_PCT,FT_PCT,PTS,PTS_RANK,AST,AST_RANK,PLUS_MINUS_RANK
0,2010-11,2011-05-10,41000205,1610612737,Atlanta Hawks,0.479,0.083,0.824,83,140,20,43,139
1,2010-11,2011-05-02,41000201,1610612737,Atlanta Hawks,0.513,0.538,0.800,103,24,20,43,39
2,2010-11,2011-05-04,41000202,1610612737,Atlanta Hawks,0.338,0.231,0.750,73,159,14,137,145
3,2010-11,2011-04-19,41000132,1610612737,Atlanta Hawks,0.395,0.350,0.647,82,144,15,123,106
4,2010-11,2011-04-26,41000135,1610612737,Atlanta Hawks,0.362,0.250,0.688,76,157,15,123,159
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2357,2023-24,2024-04-20,42300161,1610612756,Phoenix Suns,0.440,0.321,0.800,95,129,16,156,153
2358,2023-24,2024-04-20,42300131,1610612739,Cleveland Cavaliers,0.444,0.267,0.810,97,120,21,103,31
2359,2023-24,2024-04-20,42300161,1610612750,Minnesota Timberwolves,0.500,0.375,0.909,120,21,26,35,11
2360,2023-24,2024-04-20,42300111,1610612755,Philadelphia 76ers,0.444,0.343,0.909,104,92,17,149,106
2361,2023-24,2024-04-20,42300131,1610612753,Orlando Magic,0.326,0.216,0.633,83,161,16,156,133

In [4]:
regular_part_1 = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_box_scores_2010_2024_part_1.csv')

#Change season_year and game_date to date-time format
regular_part_1['game_date'] = pd.to_datetime(regular_part_1['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
#regular_part_1[(regular_part_1['season_year']>='2020-21') & (regular_part_1['season_year']<='2023-24')]
regular_part_1 = regular_part_1[regular_part_1['game_date']>='2020-03-01']

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_part_1 = regular_part_1[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamName', 'personId', 'personName', 'position', 'minutes', 'reboundsTotal','assists', 'points', 'fieldGoalsPercentage', 'threePointersPercentage', 'plusMinusPoints', 'freeThrowsPercentage']]

regular_part_1['season_year'].unique()
regular_part_1['minutes'].info()
regular_part_1

<class 'pandas.core.series.Series'>
Index: 42133 entries, 2062 to 140999
Series name: minutes
Non-Null Count  Dtype
--------------  -----
34537 non-null  object
dtypes: object(1)
memory usage: 658.3+ KB

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,position,minutes,reboundsTotal,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
2062,2019-20,2020-03-06,21900930,1610612737,ATL,Hawks,1713,Vince Carter,NaN,16:45,1,0,8,0.750,0.667,1,0.0
2084,2019-20,2020-03-09,21900957,1610612737,ATL,Hawks,1713,Vince Carter,NaN,15:08,0,1,9,0.500,0.600,0,0.0
2093,2019-20,2020-03-11,21900969,1610612737,ATL,Hawks,1713,Vince Carter,NaN,12:40,1,0,5,0.400,0.500,6,0.0
2106,2019-20,2020-03-07,21900943,1610612737,ATL,Hawks,1713,Vince Carter,NaN,18:54,2,1,5,0.286,0.167,8,0.0
2157,2019-20,2020-03-02,21900905,1610612737,ATL,Hawks,1713,Vince Carter,NaN,15:12,3,1,6,0.222,0.286,-16,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140972,2019-20,2020-03-10,21900963,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0,0.000,0.000,0,0.0
140981,2019-20,2020-03-05,21900927,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0,0.000,0.000,0,0.0
140983,2019-20,2020-08-04,21901261,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0,0.000,0.000,0,0.0
140998,2019-20,2020-08-11,21901298,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0,0.000,0.000,0,0.0
140999,2019-20,2020-08-02,21901248,1610612745,HOU,Rockets,2199,Tyson Chandler,NaN,NaN,0,0,0,0.000,0.000,0,0.0

In [5]:
regular_part_2 = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_box_scores_2010_2024_part_2.csv')

#Change season_year and game_date to date-time format
regular_part_2['game_date'] = pd.to_datetime(regular_part_2['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
#regular_part_2[(regular_part_2['season_year']>='2020-21') & (regular_part_2['season_year']<='2023-24')]
regular_part_2 = regular_part_2[regular_part_2['game_date']>='2020-03-01']

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_part_2 = regular_part_2[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamName', 'personId', 'personName', 'position', 'minutes', 'reboundsTotal', 'assists', 'points', 'fieldGoalsPercentage', 'threePointersPercentage', 'plusMinusPoints', 'freeThrowsPercentage']]
regular_part_2['season_year'].unique()
regular_part_2['minutes'].info()
regular_part_2

<class 'pandas.core.series.Series'>
Index: 42911 entries, 1441 to 140866
Series name: minutes
Non-Null Count  Dtype
--------------  -----
34785 non-null  object
dtypes: object(1)
memory usage: 670.5+ KB

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,position,minutes,reboundsTotal,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
1441,2019-20,2020-03-08,21900953,1610612745,HOU,Rockets,200757,Thabo Sefolosha,NaN,8:13,0,0,0,0.0,0.0,11,0.0
1449,2019-20,2020-03-07,21900940,1610612745,HOU,Rockets,200757,Thabo Sefolosha,NaN,NaN,0,0,0,0.0,0.0,0,0.0
1480,2019-20,2020-03-05,21900927,1610612745,HOU,Rockets,200757,Thabo Sefolosha,NaN,NaN,0,0,0,0.0,0.0,0,0.0
1487,2019-20,2020-03-10,21900963,1610612745,HOU,Rockets,200757,Thabo Sefolosha,NaN,NaN,0,0,0,0.0,0.0,0,0.0
1488,2019-20,2020-03-02,21900903,1610612745,HOU,Rockets,200757,Thabo Sefolosha,NaN,NaN,0,0,0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140862,2023-24,2023-12-29,22300429,1610612752,NYK,Knicks,1631376,Dmytro Skapintsev,NaN,NaN,0,0,0,0.0,0.0,0,0.0
140863,2023-24,2023-12-25,22300401,1610612752,NYK,Knicks,1631376,Dmytro Skapintsev,NaN,NaN,0,0,0,0.0,0.0,0,0.0
140864,2023-24,2023-12-27,22300419,1610612752,NYK,Knicks,1631376,Dmytro Skapintsev,NaN,NaN,0,0,0,0.0,0.0,0,0.0
140865,2023-24,2023-12-23,22300388,1610612752,NYK,Knicks,1631376,Dmytro Skapintsev,NaN,1:03,0,0,0,0.0,0.0,-3,0.0
140866,2023-24,2023-12-05,22301201,1610612752,NYK,Knicks,1641798,Jaylen Martin,NaN,NaN,0,0,0,0.0,0.0,0,0.0

In [6]:
regular_part_3 = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_box_scores_2010_2024_part_3.csv')

#Change season_year and game_date to date-time format
regular_part_3['game_date'] = pd.to_datetime(regular_part_3['game_date'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)

regular_part_3 = regular_part_3[regular_part_3['game_date']>='2020-03-01']
#regular_part_3['season_year'] = regular_part_3[regular_part_3['season_year'].isin(filtered_years)]


#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_part_3 = regular_part_3[['season_year', 'game_date', 'gameId', 'teamId', 'teamTricode', 'teamName', 'personId', 'personName', 'minutes', 'reboundsTotal', 'assists', 'points', 'fieldGoalsPercentage', 'threePointersPercentage', 'plusMinusPoints', 'freeThrowsPercentage']]

regular_part_3['season_year'].unique()
regular_part_3['minutes'].info()
regular_part_3

<class 'pandas.core.series.Series'>
Index: 43231 entries, 922 to 141491
Series name: minutes
Non-Null Count  Dtype
--------------  -----
35556 non-null  object
dtypes: object(1)
memory usage: 675.5+ KB

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,minutes,reboundsTotal,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
922,2019-20,2020-08-10,21901292,1610612760,OKC,Thunder,101108,Chris Paul,23:48,5,7,14,0.333,0.200,-16,1.0
925,2019-20,2020-08-01,21901240,1610612760,OKC,Thunder,101108,Chris Paul,27:07,7,7,18,0.636,1.000,27,1.0
927,2019-20,2020-08-09,21901285,1610612760,OKC,Thunder,101108,Chris Paul,32:39,6,9,13,0.444,0.750,26,1.0
930,2019-20,2020-03-06,21900932,1610612760,OKC,Thunder,101108,Chris Paul,30:16,3,12,21,0.615,0.667,12,1.0
931,2019-20,2020-03-03,21900912,1610612760,OKC,Thunder,101108,Chris Paul,30:37,2,7,14,0.455,0.500,-6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141487,2023-24,2024-01-25,22300628,1610612764,WAS,Wizards,1641998,Trey Jemison,0:50,1,0,0,0.000,0.000,0,0.0
141488,2023-24,2024-01-21,22300602,1610612764,WAS,Wizards,1641998,Trey Jemison,NaN,0,0,0,0.000,0.000,0,0.0
141489,2023-24,2024-01-29,22300665,1610612764,WAS,Wizards,1641998,Trey Jemison,NaN,0,0,0,0.000,0.000,0,0.0
141490,2023-24,2024-01-24,22300620,1610612764,WAS,Wizards,1641998,Trey Jemison,0:39,0,0,0,0.000,0.000,3,0.0
141491,2023-24,2024-01-27,22300642,1610612764,WAS,Wizards,1641998,Trey Jemison,NaN,0,0,0,0.000,0.000,0,0.0

In [7]:
regular_season_totals = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_totals_2010_2024.csv')

#Change season_year and game_date to date-time format
regular_season_totals['GAME_DATE'] = pd.to_datetime(regular_season_totals['GAME_DATE'])

##Select the range of dates between 2020 and 2024(need to go with season year bc the season overlaps 2 year. Not selecting any 24-25 data as it will be inomplete)
regular_season_totals[(regular_season_totals['SEASON_YEAR']>='2020-21') & (regular_season_totals['SEASON_YEAR']<='2023-24')]

#Select the columns I will be using to make it easier to work with(I can look at overall team ranks as well)
regular_season_totals[['SEASON_YEAR', 'GAME_DATE', 'GAME_ID', 'TEAM_ID', 'TEAM_NAME', 'FG_PCT', 'FG3_PCT', 'FT_PCT', 'AST', 'AST_RANK', 'PTS', 'PTS_RANK', 'PLUS_MINUS_RANK']]

,SEASON_YEAR,GAME_DATE,GAME_ID,TEAM_ID,TEAM_NAME,FG_PCT,FG3_PCT,FT_PCT,AST,AST_RANK,PTS,PTS_RANK,PLUS_MINUS_RANK
0,2022-23,2023-04-09,22201230,1610612744,Golden State Warriors,0.604,0.551,0.875,47,1,157,3,1
1,2020-21,2020-12-29,22000051,1610612749,Milwaukee Bucks,0.554,0.569,0.867,32,146,144,14,7
2,2013-14,2013-12-16,21300359,1610612751,Brooklyn Nets,0.603,0.600,0.577,35,22,130,19,12
3,2013-14,2013-12-14,21300347,1610612757,Portland Trail Blazers,0.559,0.568,0.700,41,2,139,4,15
4,2018-19,2019-04-07,21801200,1610612745,Houston Rockets,0.530,0.474,0.762,34,84,149,4,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33311,2022-23,2023-01-23,22200710,1610612766,Charlotte Hornets,0.447,0.125,0.706,22,1756,102,2077,2211
33312,2022-23,2023-01-29,22200754,1610612746,LA Clippers,0.416,0.105,0.852,17,2338,99,2220,2339
33313,2018-19,2019-03-23,21801090,1610612741,Chicago Bulls,0.359,0.125,0.750,16,2339,83,2439,2412
33314,2021-22,2021-10-30,22100078,1610612738,Boston Celtics,0.411,0.077,0.880,23,1407,112,1081,1321
33315,2013-14,2013-12-30,21300454,1610612763,Memphis Grizzlies,0.449,0.000,0.750,19,1681,91,1931,1417

In [8]:
# Combine the 3 regular season stats for easier analysis and remove duplicates
two_regular_season = pd.merge(regular_part_1, regular_part_2, how='outer')
#all_regular_season = all_regular_season.drop_duplicates()
two_regular_season

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,position,minutes,reboundsTotal,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
0,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,101107,Marvin Williams,NaN,19:37,2,2,0,0.000,0.000,-11,0.000
1,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,101141,Ersan Ilyasova,NaN,NaN,0,0,0,0.000,0.000,0,0.000
2,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201572,Brook Lopez,C,26:25,7,0,16,0.364,0.200,16,0.778
3,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201577,Robin Lopez,NaN,13:18,3,0,2,0.200,0.000,-12,0.000
4,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201588,George Hill,NaN,25:43,5,2,11,0.364,0.250,2,0.667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85039,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1629611,Terance Mann,G,27:40,6,2,24,0.714,0.333,-4,1.000
85040,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1629875,Xavier Moon,G,46:21,6,6,14,0.273,0.222,-7,0.000
85041,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1630527,Brandon Boston Jr.,NaN,30:53,6,3,15,0.313,0.333,-4,0.750
85042,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1630538,Bones Hyland,NaN,NaN,0,0,0,0.000,0.000,0,0.000
85043,2023-24,2024-04-14,22301199,1610612746,LAC,Clippers,1641738,Kobe Brown,NaN,38:26,6,4,9,0.400,0.333,-10,0.000

In [9]:
#merge the combined df with the 3rd regular season data
all_regular_season = pd.merge(two_regular_season, regular_part_3, how='outer')

#remove : and the seconds from the mm:ss fill NaN with 0:0 to account for errors and change to string because the object column doesnt allow
all_regular_season['minutes'] = (all_regular_season['minutes'].fillna('0:0').str.split(':').str[0].astype(int))

#filter for players that played 20 or minutes for more consistent data
all_regular_season = all_regular_season[all_regular_season['minutes'] >= 20]

all_regular_season

,season_year,game_date,gameId,teamId,teamTricode,teamName,personId,personName,position,minutes,reboundsTotal,assists,points,fieldGoalsPercentage,threePointersPercentage,plusMinusPoints,freeThrowsPercentage
2,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201572,Brook Lopez,C,26,7,0,16,0.364,0.200,16,0.778
4,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,201588,George Hill,NaN,25,5,2,11,0.364,0.250,2,0.667
5,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,202083,Wesley Matthews,F,27,8,2,8,0.273,0.286,11,0.000
6,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,202339,Eric Bledsoe,G,22,1,2,4,0.250,0.000,6,0.000
7,2019-20,2020-03-01,21900895,1610612749,MIL,Bucks,203507,Giannis Antetokounmpo,F,34,20,6,41,0.607,0.250,22,0.857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128264,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1627734,Domantas Sabonis,NaN,27,11,9,18,0.700,0.000,37,1.000
128265,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1628368,De'Aaron Fox,NaN,25,2,3,24,0.714,0.667,13,1.000
128270,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1630558,Davion Mitchell,NaN,21,4,3,11,0.364,0.600,33,0.000
128271,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1631099,Keegan Murray,NaN,27,5,1,12,0.333,0.286,26,1.000
128272,2023-24,2024-04-14,22301200,1610612758,SAC,Kings,1631165,Keon Ellis,NaN,24,3,2,13,0.444,0.500,30,1.000

In [10]:
grouped_data = all_regular_season.groupby(['season_year', 'personName','personId', 'plusMinusPoints', 'reboundsTotal']).agg({'minutes': 'mean', 'points': 'mean', 'assists': 'mean','fieldGoalsPercentage': 'mean'}).reset_index()

In [11]:
#filter for the year 2020-2021
year_2019_20 = grouped_data[grouped_data['season_year']=='2020-21']
year_2019_20

,season_year,personName,personId,plusMinusPoints,reboundsTotal,minutes,points,assists,fieldGoalsPercentage
2171,2020-21,Aaron Gordon,203932,-27,7,28.0,9.0,2.0,0.308
2172,2020-21,Aaron Gordon,203932,-23,3,20.0,6.0,1.0,0.125
2173,2020-21,Aaron Gordon,203932,-23,5,26.0,3.0,5.0,0.111
2174,2020-21,Aaron Gordon,203932,-17,5,35.0,21.0,8.0,0.571
2175,2020-21,Aaron Gordon,203932,-15,6,23.0,9.0,3.0,0.600
...,...,...,...,...,...,...,...,...,...
15536,2020-21,Zion Williamson,1629627,20,7,22.0,23.0,2.0,0.750
15537,2020-21,Zion Williamson,1629627,24,2,32.0,27.0,5.0,0.813
15538,2020-21,Zion Williamson,1629627,25,9,28.0,27.0,5.0,0.692
15539,2020-21,Zion Williamson,1629627,29,5,20.0,20.0,7.0,0.600
15540,2020-21,Zion Williamson,1629627,37,7,32.0,28.0,6.0,0.857

In [12]:
#filter for the year 2020-2021
year_2020_21 = grouped_data[grouped_data['season_year']=='2020-21']
year_2020_21

,season_year,personName,personId,plusMinusPoints,reboundsTotal,minutes,points,assists,fieldGoalsPercentage
2171,2020-21,Aaron Gordon,203932,-27,7,28.0,9.0,2.0,0.308
2172,2020-21,Aaron Gordon,203932,-23,3,20.0,6.0,1.0,0.125
2173,2020-21,Aaron Gordon,203932,-23,5,26.0,3.0,5.0,0.111
2174,2020-21,Aaron Gordon,203932,-17,5,35.0,21.0,8.0,0.571
2175,2020-21,Aaron Gordon,203932,-15,6,23.0,9.0,3.0,0.600
...,...,...,...,...,...,...,...,...,...
15536,2020-21,Zion Williamson,1629627,20,7,22.0,23.0,2.0,0.750
15537,2020-21,Zion Williamson,1629627,24,2,32.0,27.0,5.0,0.813
15538,2020-21,Zion Williamson,1629627,25,9,28.0,27.0,5.0,0.692
15539,2020-21,Zion Williamson,1629627,29,5,20.0,20.0,7.0,0.600
15540,2020-21,Zion Williamson,1629627,37,7,32.0,28.0,6.0,0.857

In [13]:
#filter for the year 2021-2022
year_2021_22 = grouped_data[grouped_data['season_year']=='2021-22']
year_2021_22

,season_year,personName,personId,plusMinusPoints,reboundsTotal,minutes,points,assists,fieldGoalsPercentage
15541,2021-22,Aaron Gordon,203932,-28,4,27.0,8.0,1.0,0.333
15542,2021-22,Aaron Gordon,203932,-27,3,27.0,9.0,0.0,0.333
15543,2021-22,Aaron Gordon,203932,-18,4,21.0,13.0,0.0,0.600
15544,2021-22,Aaron Gordon,203932,-16,4,24.0,12.0,2.0,0.455
15545,2021-22,Aaron Gordon,203932,-16,8,35.0,20.0,5.0,0.600
...,...,...,...,...,...,...,...,...,...
30519,2021-22,Ziaire Williams,1630533,14,6,28.0,9.0,0.0,0.571
30520,2021-22,Ziaire Williams,1630533,18,2,30.0,3.0,5.0,0.200
30521,2021-22,Ziaire Williams,1630533,18,3,22.0,8.0,1.0,0.429
30522,2021-22,Ziaire Williams,1630533,21,0,25.0,14.0,0.0,0.625
30523,2021-22,Ziaire Williams,1630533,32,6,21.0,16.0,1.0,0.667

In [14]:
#filter for the year 2022-2023
year_2022_23 = grouped_data[grouped_data['season_year']=='2022-23']
year_2022_23

,season_year,personName,personId,plusMinusPoints,reboundsTotal,minutes,points,assists,fieldGoalsPercentage
30524,2022-23,A.J. Lawson,1630639,-19,6,22.0,12.0,0.0,0.556
30525,2022-23,A.J. Lawson,1630639,-13,5,23.0,10.0,1.0,0.444
30526,2022-23,AJ Green,1631260,-2,2,23.0,15.0,1.0,0.625
30527,2022-23,AJ Green,1631260,9,3,21.0,7.0,1.0,0.333
30528,2022-23,AJ Griffin,1631100,-21,3,20.0,6.0,1.0,0.333
...,...,...,...,...,...,...,...,...,...
45359,2022-23,Zion Williamson,1629627,20,11,26.0,32.0,1.0,0.778
45360,2022-23,Zion Williamson,1629627,21,4,35.0,26.0,6.0,0.889
45361,2022-23,Zion Williamson,1629627,28,2,23.0,9.0,4.0,0.429
45362,2022-23,Zion Williamson,1629627,28,15,33.0,30.0,8.0,0.643
45363,2022-23,Zion Williamson,1629627,30,7,36.0,35.0,4.0,0.765

In [15]:
#filter for the year 2023-2024
year_2023_24 = grouped_data[grouped_data['season_year']=='2023-24']
year_2023_24

,season_year,personName,personId,plusMinusPoints,reboundsTotal,minutes,points,assists,fieldGoalsPercentage
45364,2023-24,A.J. Lawson,1630639,-18,5,23.0,12.0,2.0,0.385
45365,2023-24,A.J. Lawson,1630639,-4,6,21.0,2.0,2.0,0.167
45366,2023-24,A.J. Lawson,1630639,2,2,23.0,8.0,1.0,0.750
45367,2023-24,A.J. Lawson,1630639,16,7,30.0,17.0,3.0,0.700
45368,2023-24,A.J. Lawson,1630639,21,5,24.0,14.0,2.0,0.500
...,...,...,...,...,...,...,...,...,...
60076,2023-24,Zion Williamson,1629627,21,10,33.0,26.0,3.0,0.647
60077,2023-24,Zion Williamson,1629627,23,5,29.0,19.0,7.0,0.667
60078,2023-24,Zion Williamson,1629627,26,5,32.0,36.0,2.0,0.765
60079,2023-24,Zion Williamson,1629627,28,8,25.0,16.0,9.0,0.636
60080,2023-24,Zion Williamson,1629627,32,3,29.0,26.0,5.0,0.750

In [16]:
#find the agg average of 5 columns from 2022-23
performance_score5 = year_2019_20.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'reboundsTotal': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

#Calculate personal performance score to rank players

In [18]:
#find the agg average of 5 columns from 2022-23
performance_score20_21 = year_2020_21.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'reboundsTotal': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

In [20]:
#find the agg average of 5 columns from 2022-23
performance_score21_22 = year_2021_22.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'reboundsTotal': 'mean',
    'fieldGoalsPercentage': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

In [22]:
#find the agg average of 5 columns from 2022-23
performance_score22_23 = year_2022_23.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'fieldGoalsPercentage': 'mean',
    'reboundsTotal': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

In [24]:
#find the agg average of 5 columns from 2023-24
performance_score23_24 = year_2023_24.groupby(['season_year', 'personName']).agg({
    'points': 'mean',
    'assists': 'mean',
    'minutes': 'mean',
    'fieldGoalsPercentage': 'mean',
    'reboundsTotal': 'mean',
    'plusMinusPoints': 'mean'
}).reset_index()

year_2019_20.to_csv('year_2019_20.csv', index=False)

year_2020_21.to_csv('year_2020_21.csv', index=False)

year_2021_22.to_csv('year_2021_22.csv', index=False)

year_2022_23.to_csv('year_2022_23.csv', index=False)

year_2023_24.to_csv('year_2023_24.csv', index=False)